name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: l8518.azurecr.io/omniskin
          registry:  ${{ secrets.DOCKER_REGISTRY }}
          tag_with_ref: true
          tag_with_sha: true
